version: '3.1'
services: 
    
    postgres-service:
        container_name: bankaccount-postgres
        ports: 
            - "5432:5432"
        image: postgres
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=postgres

    mongodb-service:
        container_name: bankaccount-mongo
        ports: 
            - "27017:27017"
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=bankaccount
            - MONGO_INITDB_ROOT_PASSWORD=bankaccount

    zookeeper:
        container_name: bankaccount-zookeeper
        image: strimzi/kafka:0.11.3-kafka-2.1.0
        command: [
            "sh", "-c",
            "bin/zookeeper-server-start.sh config/zookeeper.properties"
        ]
        ports:
            - "2181:2181"
        environment:
            LOG_DIR: /tmp/logs
    
    kafka:
        container_name: bankaccount-kafka
        image: strimzi/kafka:0.11.3-kafka-2.1.0
        command: [
            "sh", "-c",
            "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
        ]
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            LOG_DIR: "/tmp/logs"
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181